---
 - name: creation utilisateurs
   hosts: all
   become: yes
   remote_user: thomas
   roles:
    - user
  
- name: installation serveur web
   hosts: [web]
   roles:
    - webserver
    
- name: installation mariadb
  hosts: [db]
  roles:
    - database
