- name: installation mysql
    yum:
      name: "{{ item }}"
      state: present
    loop:
      "{{ mariadb_packages }}"
    when: ansible_facts['os_family'] == "RedHat"

  - name: Activation et démarrage du serveur mariadb
    systemd:
      name: mariadb
      state: started
      enabled: yes
      
  - name: Allow external MySQL connexions (1/2)
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^skip-external-locking'
      line: "# skip-external-locking"
      notify: Restart mysql
      
  - name: Allow external MySQL connexions (2/2)
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: "# bind-address"
    notify: Restart mysql
